# Generated by Django 5.1.3 on 2024-12-24 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mydb", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.CharField(max_length=16, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=20)),
                ("contact_info", models.CharField(max_length=20, null=True)),
            ],
            options={
                "db_table": "admin",
            },
        ),
        migrations.CreateModel(
            name="Owner",
            fields=[
                (
                    "id",
                    models.CharField(max_length=16, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=20)),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")], max_length=6
                    ),
                ),
                ("phone_number", models.CharField(max_length=15, null=True)),
                ("address", models.CharField(max_length=150, null=True)),
            ],
            options={
                "db_table": "owner",
            },
        ),
        migrations.CreateModel(
            name="Record",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("entry_time", models.DateTimeField()),
                ("exit_time", models.DateTimeField(null=True)),
                ("fee", models.DecimalField(decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                "db_table": "record",
            },
        ),
        migrations.RemoveField(
            model_name="car",
            name="Color",
        ),
        migrations.RemoveField(
            model_name="car",
            name="Model",
        ),
        migrations.AddField(
            model_name="car",
            name="status",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="ParkingSpot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parking_lot_id", models.IntegerField()),
                ("spot_id", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("Available", "Available"), ("Occupied", "Occupied")],
                        default="Available",
                        max_length=9,
                    ),
                ),
            ],
            options={
                "db_table": "parkingspot",
                "unique_together": {("parking_lot_id", "spot_id")},
            },
        ),
        migrations.AddField(
            model_name="car",
            name="color",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="car",
            name="model",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name="Own",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mydb.car"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mydb.owner"
                    ),
                ),
            ],
            options={
                "db_table": "own",
                "unique_together": {("owner", "car")},
            },
        ),
        migrations.CreateModel(
            name="Manage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mydb.admin"
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mydb.record"
                    ),
                ),
            ],
            options={
                "db_table": "manage",
                "unique_together": {("admin", "record")},
            },
        ),
        migrations.CreateModel(
            name="Have",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mydb.car"
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mydb.record"
                    ),
                ),
            ],
            options={
                "db_table": "have",
                "unique_together": {("car", "record")},
            },
        ),
        migrations.CreateModel(
            name="Where",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parking_lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mydb.parkingspot",
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mydb.record"
                    ),
                ),
            ],
            options={
                "db_table": "where",
                "unique_together": {("record", "parking_lot")},
            },
        ),
    ]
