# Generated by Django 5.1.3 on 2024-12-26 03:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mydb", "0006_alter_record_exit_time_alter_record_fee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="owner",
            name="id",
            field=models.CharField(max_length=18, primary_key=True, serialize=False),
        ),
    ]
