# Generated by Django 5.1.3 on 2024-12-24 04:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "LicensePlate",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("Model", models.CharField(max_length=100)),
                ("Color", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "car",
            },
        ),
    ]
