# Generated by Django 5.1.3 on 2024-12-24 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mydb", "0004_where_parking_spot_alter_where_parking_lot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="where",
            name="parking_spot",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="where_parking_spot",
                to="mydb.parkingspot",
            ),
        ),
    ]
